### ISSUE TITLE
Which A's are corresponding to X's

### ISSUE THREAD

**Issue by ddemirci** [CMPE482-Spring2017-Bogazici/FinalProjects#8]
Hello, 
I am confused about the equations (1) and (2) in the Project 1.
According to first equation;
X4=X3*A1 + X2*A2 + X1*A3 + X0*A4 + E4

Yet, according to second equation;

E4=X0*A1 + X1*A2 + X2*A3 + X3*A4 -X4

the orders of A's are not same in these two equations.
Did I miss something ?

**Comment by mehmetburakkurutmaz** [comment]
Thank you for noticing the mistake. First equation was correct and second equation is now corrected.
